name: CI-macOS

# Controls when the action will run. 
# Triggers the workflow on pull request events but only for the master branch.
on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-13

    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.3.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test
      run: xcodebuild clean build test -project CurrencyTracker/CurrencyTracker.xcodeproj -scheme "CurrencyTrackerCore" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
